<?php

namespace Acme\Bundle\BlogBundle\Repository;

/**
 * InvitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvitRepository extends \Doctrine\ORM\EntityRepository
{
}
